[package]
name = "aws_mock-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
aws-config = "0.53.0"
aws-sdk-config = "0.23"
aws-sdk-s3 = "0.23"
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
